services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: always
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ROOT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ROOT_PASSWORD}  
      - DOCKER_INFLUXDB_INIT_ORG=my-class
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor-data
    restart: always

  stream_server:
    image: python:3.11-slim
    container_name: stream_server
    volumes:
      - .:/app  # Mount the current directory to /app
    working_dir: /app
    # Use 'python stream_portal.py' directly, not 'python /app/stream_portal.py'
    command: >
      sh -c "pip install flask influxdb_client python-dotenv numpy pandas boto3 python-dateutil && cp .env scripts/.env && python -u scripts/stream_portal2.py"
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443" # Add this line
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/ddh-portal:/var/www/ddh-portal:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Add this line to give Nginx access to certs
    restart: always
  
  # New service for the Web Portal API
  portal_backend:
    image: node:20-slim # Using Node.js for better Clerk/MongoDB integration
    container_name: portal_api
    working_dir: /app
    volumes:
      - ./webportal-backend/:/app
      - ./env:/app/.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_ROOT_TOKEN}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"
    restart: always
